spring:
  application:
    name: catalog-service
server:
  port: ${PORT:8080}
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health,info
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    id.tokokita: DEBUG

